name: Deploy VPN

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install WireGuard
      run: |
        sudo apt update
        sudo apt install wireguard

    - name: Generate WireGuard Config
      run: |
        curl -L https://example.com/generate-wireguard-config.sh | bash

    - name: Save Config
      run: |
        mv /etc/wireguard/wg0.conf ./wg0.conf
        echo "VPN config saved to wg0.conf"
